'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test } = require('node:test');
const { createRequire } = require('node:module');
const { parseHTML } = createRequire(path.resolve(__dirname, '../../packages/core/package.json'))('linkedom');
const {
  storeAssets, replaceBundleImages, inlineUploadedAssets, imageType, relativeName,
  validateAssetImages, MAX_ASSET_BYTES, MAX_BUNDLE_BYTES,
} = require('../content-assets');

// Small original raster fixtures generated by a real Chrome canvas (PNG/JPEG/WebP).
const PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAEklEQVR4AWJiWLDgPwgzMUABAAAA///8VI8uAAAABklEQVQDADnwBIOeWLgLAAAAAElFTkSuQmCC';
const JPEG_BASE64 = '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAACAAIDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAABwj/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCUAJCKn//Z';
const WEBP_BASE64 = 'UklGRhwCAABXRUJQVlA4WAoAAAAgAAAAAQAAAQAASUNDUMgBAAAAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADZWUDggLgAAAJABAJ0BKgIAAgABQCYloAJ0ugADmAD+6Di/3BmfV2OH/3T1/3eb/7eb/YUAAAA=';
const GIF_BASE64 = 'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
const PNG = Buffer.from(PNG_BASE64, 'base64');
const fixtures = [
  ['original.png', PNG_BASE64, 'image/png'], ['original.jpg', JPEG_BASE64, 'image/jpeg'],
  ['original.gif', GIF_BASE64, 'image/gif'], ['original.webp', WEBP_BASE64, 'image/webp'],
];
const asset = (name = 'chart.png', dataBase64 = PNG_BASE64) => ({ name, dataBase64 });

function scratch(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'content-assets-test-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  return root;
}
function crc32(bytes) {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let i = 0; i < 8; i++) crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const result = Buffer.alloc(data.length + 12);
  result.writeUInt32BE(data.length, 0); result.write(type, 4); data.copy(result, 8);
  result.writeUInt32BE(crc32(result.subarray(4, result.length - 4)), result.length - 4);
  return result;
}
function header(width, height) {
  const data = Buffer.from(PNG.subarray(16, 29));
  data.writeUInt32BE(width, 0); data.writeUInt32BE(height, 4);
  return Buffer.concat([PNG.subarray(0, 8), chunk('IHDR', data), PNG.subarray(33)]);
}
function brokenCompressedPNG() {
  return Buffer.concat([PNG.subarray(0, 33), chunk('IDAT', Buffer.from('this is not a zlib stream')), chunk('IEND', Buffer.alloc(0))]);
}
function animatedGIF(count) {
  const gif = Buffer.from(GIF_BASE64, 'base64');
  const image = gif.indexOf(0x2c, 13);
  return Buffer.concat([gif.subarray(0, image), ...Array.from({ length: count }, () => gif.subarray(image, -1)), Buffer.from([0x3b])]);
}

test('P1 blocks absolute, file, relative and encoded local src before any local file read', t => {
  const root = scratch(t);
  const uploads = path.join(root, 'uploads'); fs.mkdirSync(uploads);
  const outside = path.join(root, '秘密原图.png'); fs.writeFileSync(outside, PNG);
  const read = t.mock.method(fs, 'readFileSync', () => { assert.fail('unimported local source must never be read'); });
  const sources = [outside, `file://${outside}`, '../秘密.png', 'assets/chart.png', '/Users/owner/key.png', 'C:\\Users\\owner\\x.png',
    '/%55sers/owner/key.png', '%2fUsers%2fowner%2fkey.png', '%66ile%3a%2f%2f%2ftmp/a.png', '/uploads/%2e%2e/key.png',
    '/uploads/%252e%252e/key.png', '//example.com/file.png', '/uploads/a%00.png'];
  for (const src of sources) {
    for (const html of [`<img src="${src}">`, `<img SRC='${src}'>`, `<IMG src=${src}>`]) assert.throws(() => inlineUploadedAssets(html, uploads));
  }
  assert.throws(() => inlineUploadedAssets('<img src="&#x2f;Users&#x2f;owner/key.png">', uploads));
  assert.throws(() => inlineUploadedAssets('<img src="file&#58;///tmp/private.png">', uploads));
  assert.equal(read.mock.callCount(), 0);
});

test('P1 blocks private/loopback addresses and credential-bearing URLs', () => {
  for (const src of ['http://localhost/x.png', 'http://localhost./x.png', 'http://127.0.0.1/x.png', 'http://0177.1/x.png',
    'http://2130706433/x.png', 'http://10.1.2.3/x.png', 'http://172.31.0.1/x.png', 'http://192.168.1.1/x.png',
    'http://169.254.169.254/x.png', 'http://100.64.0.1/x.png', 'http://[::1]/x.png', 'http://[::ffff:127.0.0.1]/x.png',
    'https://user:secret@example.com/a.png', 'http://printer/x.png', 'https://example.com\\@localhost/a.png']) {
    assert.throws(() => inlineUploadedAssets(`<img src="${src}">`, '/unused'), error => !error.message.includes('secret'));
  }
});

test('P1 inlines only realpath-confined uploads, including Unicode, entities and encoded paths', t => {
  const root = scratch(t);
  fs.mkdirSync(path.join(root, '配图'));
  fs.writeFileSync(path.join(root, '配图', '测试.png'), PNG);
  const variants = ['/uploads/配图/测试.png', '/uploads/%E9%85%8D%E5%9B%BE/%E6%B5%8B%E8%AF%95.png',
    '/%75ploads/配图/测试.png?version=2', '&#47;uploads/配图/测试.png'];
  for (const src of variants) {
    const html = `<p>前文</p><img src=${src} alt="位置"><p>后文</p>`;
    const output = inlineUploadedAssets(html, root);
    const img = parseHTML(output).document.querySelector('img');
    assert.equal(img.getAttribute('src'), `data:image/png;base64,${PNG_BASE64}`);
    assert.equal(img.getAttribute('alt'), '位置');
    assert.ok(output.indexOf('前文') < output.indexOf('<img') && output.indexOf('<img') < output.indexOf('后文'));
    assert.deepEqual(fs.readFileSync(path.join(root, '配图', '测试.png')), PNG);
  }
});

test('P1 rejects upload symlinks escaping root, directories, missing and corrupt files', t => {
  const root = scratch(t), uploads = path.join(root, 'uploads'); fs.mkdirSync(uploads);
  fs.writeFileSync(path.join(root, 'outside.png'), PNG);
  fs.symlinkSync(path.join(root, 'outside.png'), path.join(uploads, 'escape.png'));
  fs.writeFileSync(path.join(uploads, 'broken.png'), PNG.subarray(0, 24));
  fs.mkdirSync(path.join(uploads, 'folder.png'));
  for (const filename of ['escape.png', 'broken.png', 'folder.png', 'missing.png']) assert.throws(() => inlineUploadedAssets(`<img src=/uploads/${filename}>`, uploads));
});

test('P1 preserves public and valid data images, removes alternate source attributes', () => {
  const html = `<picture><source srcset="/Users/private.png"><img src='HTTPS://Example.COM/图.png' srcset='/tmp/a.png 2x' data-src='/tmp/b.png' data-original='/tmp/c.png' evil-src='/tmp/d.png' alt='原图'></picture><img src="data:image/png;base64,${PNG_BASE64}">`;
  const output = inlineUploadedAssets(html, '/unused');
  assert.match(output, /https:\/\/example\.com\/%E5%9B%BE\.png/);
  assert.match(output, /alt="原图"/);
  assert.doesNotMatch(output, /\/tmp\/|\/Users\/|srcset|data-src|evil-src|<source/);
  assert.equal(parseHTML(output).document.querySelectorAll('img').length, 2);
  assert.throws(() => inlineUploadedAssets('<img src="data:image/svg+xml;base64,PHN2Zz4=">', '/unused'), /仅支持/);
  assert.throws(() => inlineUploadedAssets(`<img src="data:image/jpeg;base64,${PNG_BASE64}">`, '/unused'), /类型/);
});

test('P1 closes raw CLI scanner gaps in templates, comments, script strings and Markdown image literals', () => {
  for (const html of ['<template><img src=/Users/private.png></template>', '<!--<img src="/Users/private.png">-->',
    '<script>const text = "<img src=/Users/private.png>"</script>', '<!--<img data-src="/Users/private.png">-->',
    '<img src=/Users/private.png', '<img src="/Users/private.png"', '<template><img src=/Users/private.png',
    '<img alt=">" src="/Users/private.png"',
    '<code>![demo](/Users/private.png)</code>', '<img src="https://example.com/a.png" alt="src=\'/Users/private.png\'">']) {
    assert.throws(() => inlineUploadedAssets(html, '/unused'));
  }
  const harmless = '<pre>&lt;img src="/uploads/not-a-file.png"&gt;</pre>';
  assert.equal(inlineUploadedAssets(harmless, '/unused'), harmless);
});

test('P2#9 refuses basename fallback when both directories differ, even with common suffixes', () => {
  for (const [ref, stored] of [['customer-A/chart.png', 'customer-B/chart.png'], ['assets/chart.png', 'customer/assets/chart.png']]) {
    const records = [{ originalPath: stored, url: '/uploads/chart.png' }];
    assert.throws(() => replaceBundleImages(`<img src="${ref}">`, records), /未找到|重名/);
    const loose = replaceBundleImages(`<img src="${ref}">`, records, { strict: false });
    assert.equal(loose.warnings.length, 1);
    assert.ok(loose.html.includes(ref));
  }
});

test('P2#9 allows exact paths and unique flat selections; rejects every ambiguous basename', () => {
  const records = [{ originalPath: 'customer-A/chart.png', url: '/uploads/A.png' }, { originalPath: 'customer-B/chart.png', url: '/uploads/B.png' }];
  assert.match(replaceBundleImages('<img src="customer-A/chart.png">', records).html, /\/uploads\/A.png/);
  assert.throws(() => replaceBundleImages('<img src="chart.png">', records), /重名/);
  assert.match(replaceBundleImages('<img src="assets/chart.png">', [{ originalPath: 'chart.png', url: '/uploads/flat.png' }]).html, /\/uploads\/flat.png/);
  assert.match(replaceBundleImages('<img src="chart.png">', [records[0]]).html, /\/uploads\/A.png/);
  assert.throws(() => replaceBundleImages('<img src="assets/chart.png">', [{ originalPath: 'chart.png', url: '/uploads/flat.png' }, records[0]]), /重名/);
  assert.throws(() => replaceBundleImages('<img src="chart.png">', [{ originalPath: 'chart.png', url: '/uploads/a.png' }, { originalPath: 'chart.png', url: '/uploads/b.png' }]), /重名/);
  assert.match(replaceBundleImages('<img src="assets/%E6%B5%8B%E8%AF%95.png">', [{ originalPath: '测试.png', url: '/uploads/unicode.png' }]).html, /\/uploads\/unicode.png/);
});

test('P2#10 rejects 24-byte PNG signatures, invalid CRC and truncated structures of all four formats', t => {
  const root = scratch(t), uploads = path.join(root, 'uploads');
  assert.throws(() => imageType(PNG.subarray(0, 24)), /完整|损坏/);
  assert.throws(() => storeAssets([asset('broken.png', PNG.subarray(0, 24).toString('base64'))], uploads));
  assert.ok(!fs.existsSync(uploads), 'all synchronous checks must finish before creating the store');
  const badCRC = Buffer.from(PNG); badCRC[badCRC.length - 1] ^= 1;
  assert.throws(() => imageType(badCRC), /损坏/);
  for (const [, base64] of fixtures) {
    const bytes = Buffer.from(base64, 'base64');
    assert.throws(() => imageType(bytes.subarray(0, -1)));
    assert.throws(() => imageType(bytes.subarray(0, 24)));
  }
});

test('synchronous checks preserve real raster originals byte-for-byte and storeAssets stays synchronous', t => {
  const root = scratch(t);
  const inputs = fixtures.map(([name, dataBase64]) => Object.freeze({ name, dataBase64 }));
  const records = storeAssets(inputs, root);
  assert.ok(Array.isArray(records));
  assert.equal(records.length, 4);
  for (let i = 0; i < records.length; i++) {
    assert.deepEqual(fs.readFileSync(path.join(root, records[i].filename)), Buffer.from(inputs[i].dataBase64, 'base64'));
    assert.equal(records[i].mimeType, fixtures[i][2]);
    const info = imageType(Buffer.from(inputs[i].dataBase64, 'base64'));
    assert.ok(info.width > 0 && info.height > 0);
  }
  assert.deepEqual(storeAssets(inputs, root), records);
});

test('base64, traversal, duplicate Unicode paths, byte budgets and 40-image limit are enforced before decode', async t => {
  const root = scratch(t);
  const neverLaunch = { launch() { assert.fail('invalid bundle must not start Chrome'); } };
  for (const value of ['AB==', 'AAAA====', 'AAAA\n', '', PNG_BASE64 + '=', '*AAA']) {
    assert.throws(() => storeAssets([asset('x.png', value)], root));
    await assert.rejects(validateAssetImages([asset('x.png', value)], { chromium: neverLaunch }));
  }
  for (const name of ['../a.png', '/tmp/a.png', '%252e%252e/a.png', 'a/%2e%2e/b.png', 'C:\\a.png']) assert.throws(() => relativeName(name));
  assert.throws(() => storeAssets([asset('é.png'), asset('e\u0301.png')], root), /重复/);
  await assert.rejects(validateAssetImages(Array.from({ length: 41 }, (_, i) => asset(`${i}.png`)), { chromium: neverLaunch }), /40/);
  await assert.rejects(validateAssetImages([asset('big.png', 'A'.repeat(Math.ceil(MAX_ASSET_BYTES / 3) * 4 + 4))], { chromium: neverLaunch }), /大小/);
  const padded = Buffer.concat([PNG.subarray(0, -12), chunk('tEXt', Buffer.alloc(7 * 1024 * 1024, 65)), PNG.subarray(-12)]).toString('base64');
  assert.ok(Buffer.from(padded, 'base64').length * 4 > MAX_BUNDLE_BYTES);
  await assert.rejects(validateAssetImages(Array.from({ length: 4 }, (_, i) => asset(`${i}.png`, padded)), { chromium: neverLaunch }), /24 MiB/);
});

test('dimensions, animation frames and cumulative decoded pixels stop decompression bombs before Chrome', async () => {
  const neverLaunch = { launch() { assert.fail('pixel/animation limit must not start Chrome'); } };
  assert.throws(() => imageType(header(100000, 100000)), /尺寸|像素/);
  assert.throws(() => imageType(animatedGIF(101)), /动画帧/);
  const huge = header(4096, 4096).toString('base64');
  await assert.rejects(validateAssetImages(Array.from({ length: 4 }, (_, i) => asset(`${i}.png`, huge)), { chromium: neverLaunch }), /累计解码像素/);
  await assert.rejects(validateAssetImages([asset()], { chromium: neverLaunch, maxDimension: 1 }), /尺寸/);
});

test('empty validation is a no-op and decoder failures/timeouts close the browser without leaking input', async () => {
  assert.deepEqual(await validateAssetImages([]), []);
  let closed = 0, launchOptions, contextOptions, routeHandler, generated;
  const page = { goto: async () => {}, evaluate: async () => { throw new Error('token=secret-data'); } };
  const chromium = { launch: async opts => {
    launchOptions = opts;
    return { close: async () => { closed++; }, newContext: async opts2 => {
      contextOptions = opts2;
      return { route: async (_, handler) => { routeHandler = handler; }, newPage: async () => page };
    } };
  } };
  await assert.rejects(validateAssetImages([asset()], { chromium }), error => /解码失败/.test(error.message) && !error.message.includes('secret'));
  assert.equal(closed, 1);
  assert.equal(launchOptions.headless, true);
  assert.deepEqual(contextOptions, { javaScriptEnabled: false, offline: true, serviceWorkers: 'block', acceptDownloads: false });
  let aborted;
  await routeHandler({ request: () => ({ url: () => 'https://example.com/steal', isNavigationRequest: () => true }), abort: code => { aborted = code; } });
  assert.equal(aborted, 'blockedbyclient');
  await routeHandler({ request: () => ({ url: () => 'https://asset-decoder.invalid/', isNavigationRequest: () => true }), fulfill: response => { generated = response.body; } });
  assert.match(generated, /default-src 'none'; script-src 'none'/);
  assert.ok(!generated.includes(PNG_BASE64));
  page.evaluate = () => new Promise(() => {});
  await assert.rejects(validateAssetImages([asset()], { chromium, timeoutMs: 30 }), /超时/);
  assert.equal(closed, 2);
});

test('real Chrome decodes all four formats and every GIF animation frame without writing or changing originals', {
  skip: process.env.RUN_ASSET_IMAGE_CHROME !== '1', timeout: 60000,
}, async t => {
  const root = scratch(t);
  const inputs = Object.freeze([...fixtures.map(([name, dataBase64]) => Object.freeze({ name, dataBase64 })),
    Object.freeze(asset('animated.gif', animatedGIF(2).toString('base64')))]);
  const original = JSON.stringify(inputs);
  const decoded = await validateAssetImages(inputs);
  assert.equal(decoded.length, inputs.length);
  assert.deepEqual(decoded.map(x => x.mimeType), [...fixtures.map(f => f[2]), 'image/gif']);
  assert.equal(decoded[4].frames, 2);
  assert.equal(JSON.stringify(inputs), original);
  assert.deepEqual(fs.readdirSync(root), []);
  t.diagnostic(`Chrome ImageDecoder 实际解码 ${decoded.length} 张图片，共 ${decoded.reduce((n, a) => n + a.frames, 0)} 帧`);
});

test('real Chrome rejects corrupt compressed image data even with a correct PNG header and CRC', {
  skip: process.env.RUN_ASSET_IMAGE_CHROME !== '1', timeout: 60000,
}, async () => {
  const broken = brokenCompressedPNG();
  assert.equal(imageType(broken).mimeType, 'image/png', 'sync checks are structural, never claim full decoding');
  await assert.rejects(validateAssetImages([asset('bad-deflate.png', broken.toString('base64'))]), /无法完整解码/);
});
